[package]
name = "action_inbox_canister"
version.workspace = true
edition.workspace = true

[dependencies]
candid = { workspace = true }
candid_gen = { path = "../../../libraries/candid_gen" }
oc_error_codes = { path = "../../../libraries/error_codes" }
serde = { workspace = true }
serde_bytes = { workspace = true }
types = { path = "../../../libraries/types" }
