use crate::{RuntimeState, mutate_state};
use canister_api_macros::update;
use canister_tracing_macros::trace;
use user_index_canister::revoke_ai_app_user_key::{Response::*, *};

// The CONSUMER-APP side of a one-sided disconnect: when a user disconnects inside the app (the app
// deletes its private key), the app calls this so OpenChat drops the now-useless public key too.
// With the key gone, the in-chat propose flow re-detects "not linked" and re-offers the pairing
// sheet — the user is prompted to reconnect right where they are.
//
// Deliberately NO caller guard, and exposed over candid as well as msgpack (external apps call it
// with whatever principal they have). The authorization is knowledge of the EXACT registered PEM:
// per-user keys are generated by and known only to the app that registered them (my_ai_app_keys is
// caller-scoped and OpenChat never publishes them), so presenting the full PEM is proof the caller
// is the key's owner side. Worst case for a leaked PEM is removal of that one key — a nuisance
// (re-pair to fix), never data exposure; the private key never existed here.
// TODO(rate-limit): as with claim_ai_app_link_code, upstream should consider throttling failed
// revokes per caller so the endpoint cannot be used to probe for registered keys.
#[update(candid = true, msgpack = true)]
#[trace]
fn revoke_ai_app_user_key(args: Args) -> Response {
    mutate_state(|state| revoke_ai_app_user_key_impl(args, state))
}

fn revoke_ai_app_user_key_impl(args: Args, state: &mut RuntimeState) -> Response {
    if state.data.ai_app_user_keys.remove_by_key(&args.public_key) > 0 { Success } else { KeyNotFound }
}
